### ISSUE TITLE
!dc 

### ISSUE THREAD

**Issue by Isebella** [zeratul0/aiurbot#4]
doesnt always remember users correctly and also you can't dc lookup other users within the plug community when they come back

**Comment by zeratul0** [comment]
Are you sure that their position hasn't already cycled through? their saved position moves up the waitlist whenever a new song plays and will be removed if they were supposed to reach the booth.

also there's no dclookup command at the moment, i'll consider adding that

**Comment by Isebella** [comment]
Yeah your right the position cycles through and yes that would be helpful if there was a dclookup command thanks 👍
